import { youtubeVideoId, isSafeUrl, normalizeResources, withResources, resourcePreview } from "../src/lib/resources";
import { validatePackage } from "../src/lib/caselab-package";
console.log("D1", youtubeVideoId("https://www.youtube.com/watch?v=dQw4w9WgXcQ"));
console.log("D2", youtubeVideoId("https://youtu.be/dQw4w9WgXcQ?t=30"));
console.log("D3", youtubeVideoId("https://www.youtube.com/shorts/abc12345678"));
console.log("G", isSafeUrl("javascript:alert(1)"), isSafeUrl("data:text/html,x"), isSafeUrl(""), isSafeUrl("nope"), isSafeUrl("https://systime.dk/a"));
console.log("H", JSON.stringify(resourcePreview({title:"Kapitel 5.2", url:"https://systime.dk/kapitel"})));
console.log("YT", JSON.stringify(resourcePreview({title:"Video", url:"https://youtu.be/dQw4w9WgXcQ"})));
const pkg = { caselab_version:"2.0", package_type:"blocks", blocks:[{type:"teacher_content",title:"Læs kapitel 5.2",duration_minutes:15,student_instructions:"Læs",teacher_notes:"",content:{body:"Læs kapitlet."},resources:[{title:"Kapitel 5.2 i iBog",url:"https://example.com/kapitel-5-2"},{title:"Video",url:"https://youtu.be/dQw4w9WgXcQ"},{title:"Bad",url:"javascript:alert(1)"}]}]};
const r = validatePackage(JSON.stringify(pkg));
console.log("I", r.ok, JSON.stringify((r.data as any)?.blocks[0].resources));
const legacy = { caselab_version:"2.0", package_type:"blocks", blocks:[{type:"poll",title:"P",duration_minutes:5,content:{question:"q",options:["a","b"]}}]};
const r2 = validatePackage(JSON.stringify(legacy));
console.log("J", r2.ok, JSON.stringify((r2.data as any)?.blocks[0].resources ?? null), r2.errors);
console.log("W", JSON.stringify(withResources({body:"x"}, [{title:"",url:"https://systime.dk/a"},{title:"t",url:"bad"}])));
