/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCreateWithChatgptRouteImport } from './routes/_authenticated/create-with-chatgpt'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedUnitsRouteImport } from './routes/_authenticated/units'
import { Route as AuthenticatedClassesIndexRouteImport } from './routes/_authenticated/classes.index'
import { Route as AuthenticatedClassesClassIdRouteImport } from './routes/_authenticated/classes.$classId'
import { Route as AuthenticatedLessonsIndexRouteImport } from './routes/_authenticated/lessons.index'
import { Route as AuthenticatedLessonsNewRouteImport } from './routes/_authenticated/lessons.new'
import { Route as LessonsLessonIdRunRouteImport } from './routes/lessons.$lessonId.run'
import { Route as AuthenticatedLessonsLessonIdEditRouteImport } from './routes/_authenticated/lessons.$lessonId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCreateWithChatgptRoute =
  AuthenticatedCreateWithChatgptRouteImport.update({
    id: '/create-with-chatgpt',
    path: '/create-with-chatgpt',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUnitsRoute = AuthenticatedUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClassesIndexRoute =
  AuthenticatedClassesIndexRouteImport.update({
    id: '/classes/',
    path: '/classes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClassesClassIdRoute =
  AuthenticatedClassesClassIdRouteImport.update({
    id: '/classes/$classId',
    path: '/classes/$classId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLessonsIndexRoute =
  AuthenticatedLessonsIndexRouteImport.update({
    id: '/lessons/',
    path: '/lessons/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLessonsNewRoute = AuthenticatedLessonsNewRouteImport.update({
  id: '/lessons/new',
  path: '/lessons/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LessonsLessonIdRunRoute = LessonsLessonIdRunRouteImport.update({
  id: '/lessons/$lessonId/run',
  path: '/lessons/$lessonId/run',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLessonsLessonIdEditRoute =
  AuthenticatedLessonsLessonIdEditRouteImport.update({
    id: '/lessons/$lessonId/edit',
    path: '/lessons/$lessonId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create-with-chatgpt': typeof AuthenticatedCreateWithChatgptRoute
  '/home': typeof AuthenticatedHomeRoute
  '/import': typeof AuthenticatedImportRoute
  '/units': typeof AuthenticatedUnitsRoute
  '/classes/$classId': typeof AuthenticatedClassesClassIdRoute
  '/lessons/new': typeof AuthenticatedLessonsNewRoute
  '/lessons/$lessonId/run': typeof LessonsLessonIdRunRoute
  '/classes/': typeof AuthenticatedClassesIndexRoute
  '/lessons/': typeof AuthenticatedLessonsIndexRoute
  '/lessons/$lessonId/edit': typeof AuthenticatedLessonsLessonIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create-with-chatgpt': typeof AuthenticatedCreateWithChatgptRoute
  '/home': typeof AuthenticatedHomeRoute
  '/import': typeof AuthenticatedImportRoute
  '/units': typeof AuthenticatedUnitsRoute
  '/classes/$classId': typeof AuthenticatedClassesClassIdRoute
  '/lessons/new': typeof AuthenticatedLessonsNewRoute
  '/lessons/$lessonId/run': typeof LessonsLessonIdRunRoute
  '/classes': typeof AuthenticatedClassesIndexRoute
  '/lessons': typeof AuthenticatedLessonsIndexRoute
  '/lessons/$lessonId/edit': typeof AuthenticatedLessonsLessonIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/create-with-chatgpt': typeof AuthenticatedCreateWithChatgptRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/units': typeof AuthenticatedUnitsRoute
  '/_authenticated/classes/$classId': typeof AuthenticatedClassesClassIdRoute
  '/_authenticated/lessons/new': typeof AuthenticatedLessonsNewRoute
  '/lessons/$lessonId/run': typeof LessonsLessonIdRunRoute
  '/_authenticated/classes/': typeof AuthenticatedClassesIndexRoute
  '/_authenticated/lessons/': typeof AuthenticatedLessonsIndexRoute
  '/_authenticated/lessons/$lessonId/edit': typeof AuthenticatedLessonsLessonIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/create-with-chatgpt'
    | '/home'
    | '/import'
    | '/units'
    | '/classes/$classId'
    | '/lessons/new'
    | '/lessons/$lessonId/run'
    | '/classes/'
    | '/lessons/'
    | '/lessons/$lessonId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/create-with-chatgpt'
    | '/home'
    | '/import'
    | '/units'
    | '/classes/$classId'
    | '/lessons/new'
    | '/lessons/$lessonId/run'
    | '/classes'
    | '/lessons'
    | '/lessons/$lessonId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/create-with-chatgpt'
    | '/_authenticated/home'
    | '/_authenticated/import'
    | '/_authenticated/units'
    | '/_authenticated/classes/$classId'
    | '/_authenticated/lessons/new'
    | '/lessons/$lessonId/run'
    | '/_authenticated/classes/'
    | '/_authenticated/lessons/'
    | '/_authenticated/lessons/$lessonId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LessonsLessonIdRunRoute: typeof LessonsLessonIdRunRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/create-with-chatgpt': {
      id: '/_authenticated/create-with-chatgpt'
      path: '/create-with-chatgpt'
      fullPath: '/create-with-chatgpt'
      preLoaderRoute: typeof AuthenticatedCreateWithChatgptRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/units': {
      id: '/_authenticated/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof AuthenticatedUnitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes/': {
      id: '/_authenticated/classes/'
      path: '/classes'
      fullPath: '/classes/'
      preLoaderRoute: typeof AuthenticatedClassesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes/$classId': {
      id: '/_authenticated/classes/$classId'
      path: '/classes/$classId'
      fullPath: '/classes/$classId'
      preLoaderRoute: typeof AuthenticatedClassesClassIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lessons/': {
      id: '/_authenticated/lessons/'
      path: '/lessons'
      fullPath: '/lessons/'
      preLoaderRoute: typeof AuthenticatedLessonsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lessons/new': {
      id: '/_authenticated/lessons/new'
      path: '/lessons/new'
      fullPath: '/lessons/new'
      preLoaderRoute: typeof AuthenticatedLessonsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lessons/$lessonId/run': {
      id: '/lessons/$lessonId/run'
      path: '/lessons/$lessonId/run'
      fullPath: '/lessons/$lessonId/run'
      preLoaderRoute: typeof LessonsLessonIdRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/lessons/$lessonId/edit': {
      id: '/_authenticated/lessons/$lessonId/edit'
      path: '/lessons/$lessonId/edit'
      fullPath: '/lessons/$lessonId/edit'
      preLoaderRoute: typeof AuthenticatedLessonsLessonIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCreateWithChatgptRoute: typeof AuthenticatedCreateWithChatgptRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedUnitsRoute: typeof AuthenticatedUnitsRoute
  AuthenticatedClassesClassIdRoute: typeof AuthenticatedClassesClassIdRoute
  AuthenticatedLessonsNewRoute: typeof AuthenticatedLessonsNewRoute
  AuthenticatedClassesIndexRoute: typeof AuthenticatedClassesIndexRoute
  AuthenticatedLessonsIndexRoute: typeof AuthenticatedLessonsIndexRoute
  AuthenticatedLessonsLessonIdEditRoute: typeof AuthenticatedLessonsLessonIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCreateWithChatgptRoute: AuthenticatedCreateWithChatgptRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedUnitsRoute: AuthenticatedUnitsRoute,
  AuthenticatedClassesClassIdRoute: AuthenticatedClassesClassIdRoute,
  AuthenticatedLessonsNewRoute: AuthenticatedLessonsNewRoute,
  AuthenticatedClassesIndexRoute: AuthenticatedClassesIndexRoute,
  AuthenticatedLessonsIndexRoute: AuthenticatedLessonsIndexRoute,
  AuthenticatedLessonsLessonIdEditRoute: AuthenticatedLessonsLessonIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LessonsLessonIdRunRoute: LessonsLessonIdRunRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
