/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedCreateWithChatgptRouteImport } from './routes/_authenticated/create-with-chatgpt'
import { Route as AuthenticatedDifferentiateRouteImport } from './routes/_authenticated/differentiate'
import { Route as AuthenticatedExtraTimeRouteImport } from './routes/_authenticated/extra-time'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedImproveLessonRouteImport } from './routes/_authenticated/improve-lesson'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedMaterialToLessonRouteImport } from './routes/_authenticated/material-to-lesson'
import { Route as AuthenticatedMaterialsRouteImport } from './routes/_authenticated/materials'
import { Route as AuthenticatedRescueRouteImport } from './routes/_authenticated/rescue'
import { Route as AuthenticatedUnitsRouteImport } from './routes/_authenticated/units'
import { Route as JoinIndexRouteImport } from './routes/join.index'
import { Route as JoinCodeRouteImport } from './routes/join.$code'
import { Route as StudentCodeRouteImport } from './routes/student.$code'
import { Route as AuthenticatedClassesIndexRouteImport } from './routes/_authenticated/classes.index'
import { Route as AuthenticatedClassesClassIdRouteImport } from './routes/_authenticated/classes.$classId'
import { Route as AuthenticatedLessonsIndexRouteImport } from './routes/_authenticated/lessons.index'
import { Route as AuthenticatedLessonsNewRouteImport } from './routes/_authenticated/lessons.new'
import { Route as AuthenticatedSessionsIndexRouteImport } from './routes/_authenticated/sessions.index'
import { Route as AuthenticatedSessionsSessionIdRouteImport } from './routes/_authenticated/sessions.$sessionId'
import { Route as AuthenticatedSessionsCompareRouteImport } from './routes/_authenticated/sessions.compare'
import { Route as AuthenticatedWorldsIndexRouteImport } from './routes/_authenticated/worlds.index'
import { Route as AuthenticatedWorldsWorldIdRouteImport } from './routes/_authenticated/worlds.$worldId'
import { Route as AuthenticatedWorldsNewRouteImport } from './routes/_authenticated/worlds.new'
import { Route as LessonsLessonIdRunRouteImport } from './routes/lessons.$lessonId.run'
import { Route as AuthenticatedLessonsLessonIdEditRouteImport } from './routes/_authenticated/lessons.$lessonId.edit'
import { Route as AuthenticatedSessionsSessionIdFollowUpRouteImport } from './routes/_authenticated/sessions.$sessionId_.follow-up'
import { Route as AuthenticatedWorldsWorldIdEpisodesNewRouteImport } from './routes/_authenticated/worlds.$worldId_.episodes.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCreateWithChatgptRoute =
  AuthenticatedCreateWithChatgptRouteImport.update({
    id: '/create-with-chatgpt',
    path: '/create-with-chatgpt',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDifferentiateRoute =
  AuthenticatedDifferentiateRouteImport.update({
    id: '/differentiate',
    path: '/differentiate',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExtraTimeRoute = AuthenticatedExtraTimeRouteImport.update({
  id: '/extra-time',
  path: '/extra-time',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImproveLessonRoute =
  AuthenticatedImproveLessonRouteImport.update({
    id: '/improve-lesson',
    path: '/improve-lesson',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaterialToLessonRoute =
  AuthenticatedMaterialToLessonRouteImport.update({
    id: '/material-to-lesson',
    path: '/material-to-lesson',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaterialsRoute = AuthenticatedMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRescueRoute = AuthenticatedRescueRouteImport.update({
  id: '/rescue',
  path: '/rescue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUnitsRoute = AuthenticatedUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const JoinIndexRoute = JoinIndexRouteImport.update({
  id: '/join/',
  path: '/join/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCodeRoute = StudentCodeRouteImport.update({
  id: '/student/$code',
  path: '/student/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClassesIndexRoute =
  AuthenticatedClassesIndexRouteImport.update({
    id: '/classes/',
    path: '/classes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClassesClassIdRoute =
  AuthenticatedClassesClassIdRouteImport.update({
    id: '/classes/$classId',
    path: '/classes/$classId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLessonsIndexRoute =
  AuthenticatedLessonsIndexRouteImport.update({
    id: '/lessons/',
    path: '/lessons/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLessonsNewRoute = AuthenticatedLessonsNewRouteImport.update({
  id: '/lessons/new',
  path: '/lessons/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSessionsIndexRoute =
  AuthenticatedSessionsIndexRouteImport.update({
    id: '/sessions/',
    path: '/sessions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessionsSessionIdRoute =
  AuthenticatedSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessionsCompareRoute =
  AuthenticatedSessionsCompareRouteImport.update({
    id: '/sessions/compare',
    path: '/sessions/compare',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorldsIndexRoute =
  AuthenticatedWorldsIndexRouteImport.update({
    id: '/worlds/',
    path: '/worlds/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorldsWorldIdRoute =
  AuthenticatedWorldsWorldIdRouteImport.update({
    id: '/worlds/$worldId',
    path: '/worlds/$worldId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorldsNewRoute = AuthenticatedWorldsNewRouteImport.update({
  id: '/worlds/new',
  path: '/worlds/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LessonsLessonIdRunRoute = LessonsLessonIdRunRouteImport.update({
  id: '/lessons/$lessonId/run',
  path: '/lessons/$lessonId/run',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLessonsLessonIdEditRoute =
  AuthenticatedLessonsLessonIdEditRouteImport.update({
    id: '/lessons/$lessonId/edit',
    path: '/lessons/$lessonId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessionsSessionIdFollowUpRoute =
  AuthenticatedSessionsSessionIdFollowUpRouteImport.update({
    id: '/sessions/$sessionId_/follow-up',
    path: '/sessions/$sessionId/follow-up',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorldsWorldIdEpisodesNewRoute =
  AuthenticatedWorldsWorldIdEpisodesNewRouteImport.update({
    id: '/worlds/$worldId_/episodes/new',
    path: '/worlds/$worldId/episodes/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/create-with-chatgpt': typeof AuthenticatedCreateWithChatgptRoute
  '/differentiate': typeof AuthenticatedDifferentiateRoute
  '/extra-time': typeof AuthenticatedExtraTimeRoute
  '/home': typeof AuthenticatedHomeRoute
  '/import': typeof AuthenticatedImportRoute
  '/improve-lesson': typeof AuthenticatedImproveLessonRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/material-to-lesson': typeof AuthenticatedMaterialToLessonRoute
  '/materials': typeof AuthenticatedMaterialsRoute
  '/rescue': typeof AuthenticatedRescueRoute
  '/units': typeof AuthenticatedUnitsRoute
  '/join/$code': typeof JoinCodeRoute
  '/student/$code': typeof StudentCodeRoute
  '/join/': typeof JoinIndexRoute
  '/classes/$classId': typeof AuthenticatedClassesClassIdRoute
  '/lessons/new': typeof AuthenticatedLessonsNewRoute
  '/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRoute
  '/sessions/compare': typeof AuthenticatedSessionsCompareRoute
  '/worlds/$worldId': typeof AuthenticatedWorldsWorldIdRoute
  '/worlds/new': typeof AuthenticatedWorldsNewRoute
  '/lessons/$lessonId/run': typeof LessonsLessonIdRunRoute
  '/classes/': typeof AuthenticatedClassesIndexRoute
  '/lessons/': typeof AuthenticatedLessonsIndexRoute
  '/sessions/': typeof AuthenticatedSessionsIndexRoute
  '/worlds/': typeof AuthenticatedWorldsIndexRoute
  '/lessons/$lessonId/edit': typeof AuthenticatedLessonsLessonIdEditRoute
  '/sessions/$sessionId/follow-up': typeof AuthenticatedSessionsSessionIdFollowUpRoute
  '/worlds/$worldId/episodes/new': typeof AuthenticatedWorldsWorldIdEpisodesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/create-with-chatgpt': typeof AuthenticatedCreateWithChatgptRoute
  '/differentiate': typeof AuthenticatedDifferentiateRoute
  '/extra-time': typeof AuthenticatedExtraTimeRoute
  '/home': typeof AuthenticatedHomeRoute
  '/import': typeof AuthenticatedImportRoute
  '/improve-lesson': typeof AuthenticatedImproveLessonRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/material-to-lesson': typeof AuthenticatedMaterialToLessonRoute
  '/materials': typeof AuthenticatedMaterialsRoute
  '/rescue': typeof AuthenticatedRescueRoute
  '/units': typeof AuthenticatedUnitsRoute
  '/join/$code': typeof JoinCodeRoute
  '/student/$code': typeof StudentCodeRoute
  '/join': typeof JoinIndexRoute
  '/classes/$classId': typeof AuthenticatedClassesClassIdRoute
  '/lessons/new': typeof AuthenticatedLessonsNewRoute
  '/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRoute
  '/sessions/compare': typeof AuthenticatedSessionsCompareRoute
  '/worlds/$worldId': typeof AuthenticatedWorldsWorldIdRoute
  '/worlds/new': typeof AuthenticatedWorldsNewRoute
  '/lessons/$lessonId/run': typeof LessonsLessonIdRunRoute
  '/classes': typeof AuthenticatedClassesIndexRoute
  '/lessons': typeof AuthenticatedLessonsIndexRoute
  '/sessions': typeof AuthenticatedSessionsIndexRoute
  '/worlds': typeof AuthenticatedWorldsIndexRoute
  '/lessons/$lessonId/edit': typeof AuthenticatedLessonsLessonIdEditRoute
  '/sessions/$sessionId/follow-up': typeof AuthenticatedSessionsSessionIdFollowUpRoute
  '/worlds/$worldId/episodes/new': typeof AuthenticatedWorldsWorldIdEpisodesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/create-with-chatgpt': typeof AuthenticatedCreateWithChatgptRoute
  '/_authenticated/differentiate': typeof AuthenticatedDifferentiateRoute
  '/_authenticated/extra-time': typeof AuthenticatedExtraTimeRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/improve-lesson': typeof AuthenticatedImproveLessonRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/material-to-lesson': typeof AuthenticatedMaterialToLessonRoute
  '/_authenticated/materials': typeof AuthenticatedMaterialsRoute
  '/_authenticated/rescue': typeof AuthenticatedRescueRoute
  '/_authenticated/units': typeof AuthenticatedUnitsRoute
  '/join/$code': typeof JoinCodeRoute
  '/student/$code': typeof StudentCodeRoute
  '/join/': typeof JoinIndexRoute
  '/_authenticated/classes/$classId': typeof AuthenticatedClassesClassIdRoute
  '/_authenticated/lessons/new': typeof AuthenticatedLessonsNewRoute
  '/_authenticated/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRoute
  '/_authenticated/sessions/compare': typeof AuthenticatedSessionsCompareRoute
  '/_authenticated/worlds/$worldId': typeof AuthenticatedWorldsWorldIdRoute
  '/_authenticated/worlds/new': typeof AuthenticatedWorldsNewRoute
  '/lessons/$lessonId/run': typeof LessonsLessonIdRunRoute
  '/_authenticated/classes/': typeof AuthenticatedClassesIndexRoute
  '/_authenticated/lessons/': typeof AuthenticatedLessonsIndexRoute
  '/_authenticated/sessions/': typeof AuthenticatedSessionsIndexRoute
  '/_authenticated/worlds/': typeof AuthenticatedWorldsIndexRoute
  '/_authenticated/lessons/$lessonId/edit': typeof AuthenticatedLessonsLessonIdEditRoute
  '/_authenticated/sessions/$sessionId_/follow-up': typeof AuthenticatedSessionsSessionIdFollowUpRoute
  '/_authenticated/worlds/$worldId_/episodes/new': typeof AuthenticatedWorldsWorldIdEpisodesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/privacy'
    | '/terms'
    | '/create-with-chatgpt'
    | '/differentiate'
    | '/extra-time'
    | '/home'
    | '/import'
    | '/improve-lesson'
    | '/library'
    | '/material-to-lesson'
    | '/materials'
    | '/rescue'
    | '/units'
    | '/join/$code'
    | '/student/$code'
    | '/join/'
    | '/classes/$classId'
    | '/lessons/new'
    | '/sessions/$sessionId'
    | '/sessions/compare'
    | '/worlds/$worldId'
    | '/worlds/new'
    | '/lessons/$lessonId/run'
    | '/classes/'
    | '/lessons/'
    | '/sessions/'
    | '/worlds/'
    | '/lessons/$lessonId/edit'
    | '/sessions/$sessionId/follow-up'
    | '/worlds/$worldId/episodes/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/privacy'
    | '/terms'
    | '/create-with-chatgpt'
    | '/differentiate'
    | '/extra-time'
    | '/home'
    | '/import'
    | '/improve-lesson'
    | '/library'
    | '/material-to-lesson'
    | '/materials'
    | '/rescue'
    | '/units'
    | '/join/$code'
    | '/student/$code'
    | '/join'
    | '/classes/$classId'
    | '/lessons/new'
    | '/sessions/$sessionId'
    | '/sessions/compare'
    | '/worlds/$worldId'
    | '/worlds/new'
    | '/lessons/$lessonId/run'
    | '/classes'
    | '/lessons'
    | '/sessions'
    | '/worlds'
    | '/lessons/$lessonId/edit'
    | '/sessions/$sessionId/follow-up'
    | '/worlds/$worldId/episodes/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/privacy'
    | '/terms'
    | '/_authenticated/create-with-chatgpt'
    | '/_authenticated/differentiate'
    | '/_authenticated/extra-time'
    | '/_authenticated/home'
    | '/_authenticated/import'
    | '/_authenticated/improve-lesson'
    | '/_authenticated/library'
    | '/_authenticated/material-to-lesson'
    | '/_authenticated/materials'
    | '/_authenticated/rescue'
    | '/_authenticated/units'
    | '/join/$code'
    | '/student/$code'
    | '/join/'
    | '/_authenticated/classes/$classId'
    | '/_authenticated/lessons/new'
    | '/_authenticated/sessions/$sessionId'
    | '/_authenticated/sessions/compare'
    | '/_authenticated/worlds/$worldId'
    | '/_authenticated/worlds/new'
    | '/lessons/$lessonId/run'
    | '/_authenticated/classes/'
    | '/_authenticated/lessons/'
    | '/_authenticated/sessions/'
    | '/_authenticated/worlds/'
    | '/_authenticated/lessons/$lessonId/edit'
    | '/_authenticated/sessions/$sessionId_/follow-up'
    | '/_authenticated/worlds/$worldId_/episodes/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  JoinCodeRoute: typeof JoinCodeRoute
  StudentCodeRoute: typeof StudentCodeRoute
  JoinIndexRoute: typeof JoinIndexRoute
  LessonsLessonIdRunRoute: typeof LessonsLessonIdRunRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/create-with-chatgpt': {
      id: '/_authenticated/create-with-chatgpt'
      path: '/create-with-chatgpt'
      fullPath: '/create-with-chatgpt'
      preLoaderRoute: typeof AuthenticatedCreateWithChatgptRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/differentiate': {
      id: '/_authenticated/differentiate'
      path: '/differentiate'
      fullPath: '/differentiate'
      preLoaderRoute: typeof AuthenticatedDifferentiateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/extra-time': {
      id: '/_authenticated/extra-time'
      path: '/extra-time'
      fullPath: '/extra-time'
      preLoaderRoute: typeof AuthenticatedExtraTimeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/improve-lesson': {
      id: '/_authenticated/improve-lesson'
      path: '/improve-lesson'
      fullPath: '/improve-lesson'
      preLoaderRoute: typeof AuthenticatedImproveLessonRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/material-to-lesson': {
      id: '/_authenticated/material-to-lesson'
      path: '/material-to-lesson'
      fullPath: '/material-to-lesson'
      preLoaderRoute: typeof AuthenticatedMaterialToLessonRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/materials': {
      id: '/_authenticated/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof AuthenticatedMaterialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rescue': {
      id: '/_authenticated/rescue'
      path: '/rescue'
      fullPath: '/rescue'
      preLoaderRoute: typeof AuthenticatedRescueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/units': {
      id: '/_authenticated/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof AuthenticatedUnitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/join/': {
      id: '/join/'
      path: '/join'
      fullPath: '/join/'
      preLoaderRoute: typeof JoinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/$code': {
      id: '/student/$code'
      path: '/student/$code'
      fullPath: '/student/$code'
      preLoaderRoute: typeof StudentCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/classes/': {
      id: '/_authenticated/classes/'
      path: '/classes'
      fullPath: '/classes/'
      preLoaderRoute: typeof AuthenticatedClassesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes/$classId': {
      id: '/_authenticated/classes/$classId'
      path: '/classes/$classId'
      fullPath: '/classes/$classId'
      preLoaderRoute: typeof AuthenticatedClassesClassIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lessons/': {
      id: '/_authenticated/lessons/'
      path: '/lessons'
      fullPath: '/lessons/'
      preLoaderRoute: typeof AuthenticatedLessonsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lessons/new': {
      id: '/_authenticated/lessons/new'
      path: '/lessons/new'
      fullPath: '/lessons/new'
      preLoaderRoute: typeof AuthenticatedLessonsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions/': {
      id: '/_authenticated/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof AuthenticatedSessionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions/$sessionId': {
      id: '/_authenticated/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof AuthenticatedSessionsSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions/compare': {
      id: '/_authenticated/sessions/compare'
      path: '/sessions/compare'
      fullPath: '/sessions/compare'
      preLoaderRoute: typeof AuthenticatedSessionsCompareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/worlds/': {
      id: '/_authenticated/worlds/'
      path: '/worlds'
      fullPath: '/worlds/'
      preLoaderRoute: typeof AuthenticatedWorldsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/worlds/$worldId': {
      id: '/_authenticated/worlds/$worldId'
      path: '/worlds/$worldId'
      fullPath: '/worlds/$worldId'
      preLoaderRoute: typeof AuthenticatedWorldsWorldIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/worlds/new': {
      id: '/_authenticated/worlds/new'
      path: '/worlds/new'
      fullPath: '/worlds/new'
      preLoaderRoute: typeof AuthenticatedWorldsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lessons/$lessonId/run': {
      id: '/lessons/$lessonId/run'
      path: '/lessons/$lessonId/run'
      fullPath: '/lessons/$lessonId/run'
      preLoaderRoute: typeof LessonsLessonIdRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/lessons/$lessonId/edit': {
      id: '/_authenticated/lessons/$lessonId/edit'
      path: '/lessons/$lessonId/edit'
      fullPath: '/lessons/$lessonId/edit'
      preLoaderRoute: typeof AuthenticatedLessonsLessonIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions/$sessionId_/follow-up': {
      id: '/_authenticated/sessions/$sessionId_/follow-up'
      path: '/sessions/$sessionId/follow-up'
      fullPath: '/sessions/$sessionId/follow-up'
      preLoaderRoute: typeof AuthenticatedSessionsSessionIdFollowUpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/worlds/$worldId_/episodes/new': {
      id: '/_authenticated/worlds/$worldId_/episodes/new'
      path: '/worlds/$worldId/episodes/new'
      fullPath: '/worlds/$worldId/episodes/new'
      preLoaderRoute: typeof AuthenticatedWorldsWorldIdEpisodesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCreateWithChatgptRoute: typeof AuthenticatedCreateWithChatgptRoute
  AuthenticatedDifferentiateRoute: typeof AuthenticatedDifferentiateRoute
  AuthenticatedExtraTimeRoute: typeof AuthenticatedExtraTimeRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedImproveLessonRoute: typeof AuthenticatedImproveLessonRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedMaterialToLessonRoute: typeof AuthenticatedMaterialToLessonRoute
  AuthenticatedMaterialsRoute: typeof AuthenticatedMaterialsRoute
  AuthenticatedRescueRoute: typeof AuthenticatedRescueRoute
  AuthenticatedUnitsRoute: typeof AuthenticatedUnitsRoute
  AuthenticatedClassesClassIdRoute: typeof AuthenticatedClassesClassIdRoute
  AuthenticatedLessonsNewRoute: typeof AuthenticatedLessonsNewRoute
  AuthenticatedSessionsSessionIdRoute: typeof AuthenticatedSessionsSessionIdRoute
  AuthenticatedSessionsCompareRoute: typeof AuthenticatedSessionsCompareRoute
  AuthenticatedWorldsWorldIdRoute: typeof AuthenticatedWorldsWorldIdRoute
  AuthenticatedWorldsNewRoute: typeof AuthenticatedWorldsNewRoute
  AuthenticatedClassesIndexRoute: typeof AuthenticatedClassesIndexRoute
  AuthenticatedLessonsIndexRoute: typeof AuthenticatedLessonsIndexRoute
  AuthenticatedSessionsIndexRoute: typeof AuthenticatedSessionsIndexRoute
  AuthenticatedWorldsIndexRoute: typeof AuthenticatedWorldsIndexRoute
  AuthenticatedLessonsLessonIdEditRoute: typeof AuthenticatedLessonsLessonIdEditRoute
  AuthenticatedSessionsSessionIdFollowUpRoute: typeof AuthenticatedSessionsSessionIdFollowUpRoute
  AuthenticatedWorldsWorldIdEpisodesNewRoute: typeof AuthenticatedWorldsWorldIdEpisodesNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCreateWithChatgptRoute: AuthenticatedCreateWithChatgptRoute,
  AuthenticatedDifferentiateRoute: AuthenticatedDifferentiateRoute,
  AuthenticatedExtraTimeRoute: AuthenticatedExtraTimeRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedImproveLessonRoute: AuthenticatedImproveLessonRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedMaterialToLessonRoute: AuthenticatedMaterialToLessonRoute,
  AuthenticatedMaterialsRoute: AuthenticatedMaterialsRoute,
  AuthenticatedRescueRoute: AuthenticatedRescueRoute,
  AuthenticatedUnitsRoute: AuthenticatedUnitsRoute,
  AuthenticatedClassesClassIdRoute: AuthenticatedClassesClassIdRoute,
  AuthenticatedLessonsNewRoute: AuthenticatedLessonsNewRoute,
  AuthenticatedSessionsSessionIdRoute: AuthenticatedSessionsSessionIdRoute,
  AuthenticatedSessionsCompareRoute: AuthenticatedSessionsCompareRoute,
  AuthenticatedWorldsWorldIdRoute: AuthenticatedWorldsWorldIdRoute,
  AuthenticatedWorldsNewRoute: AuthenticatedWorldsNewRoute,
  AuthenticatedClassesIndexRoute: AuthenticatedClassesIndexRoute,
  AuthenticatedLessonsIndexRoute: AuthenticatedLessonsIndexRoute,
  AuthenticatedSessionsIndexRoute: AuthenticatedSessionsIndexRoute,
  AuthenticatedWorldsIndexRoute: AuthenticatedWorldsIndexRoute,
  AuthenticatedLessonsLessonIdEditRoute: AuthenticatedLessonsLessonIdEditRoute,
  AuthenticatedSessionsSessionIdFollowUpRoute:
    AuthenticatedSessionsSessionIdFollowUpRoute,
  AuthenticatedWorldsWorldIdEpisodesNewRoute:
    AuthenticatedWorldsWorldIdEpisodesNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  JoinCodeRoute: JoinCodeRoute,
  StudentCodeRoute: StudentCodeRoute,
  JoinIndexRoute: JoinIndexRoute,
  LessonsLessonIdRunRoute: LessonsLessonIdRunRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
