-- Historical migration version retained for compatibility with databases where
-- it is already recorded as applied. The Cockpit test session is now isolated
-- in supabase/fixtures/cockpit-test.sql and is never run as a schema migration.
