-- Historical migration version retained for compatibility with databases where
-- it is already recorded as applied. Environment-specific Cockpit test data is
-- intentionally not part of the production migration path. The guarded manual
-- fixture now lives at supabase/fixtures/cockpit-test.sql.
